development:
        address: 'smtp.sendgrid.net',
        port: 587,
        domain: '140.121.80.184',
        user_name: 'apikey',
        password: '',
        authentication: 'plain',
        enable_starttls_auto: true
production:
        address: 'smtp.sendgrid.net',
        port: 587,
        domain: '140.121.80.184',
        user_name: 'apikey',
        password: '',
        authentication: 'plain',
        enable_starttls_auto: true
