development:
  address: "in-v3.mailjet.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "014e195ce952d3010f1ed335f43d4630"
  password: "6f8221e967b8c65e1fc4b95fe9d9ec00"
  enable_starttls_auto: true
